_wandb:
    value:
        cli_version: 0.25.0
        e:
            hdrx3nuvs0cavaw0l16q93bs7mmvnktt:
                args:
                    - -d
                    - mnist
                    - -e
                    - "5"
                    - -b
                    - "64"
                    - -l
                    - cross_entropy
                    - -o
                    - momentum
                    - -lr
                    - "0.0005"
                    - -wd
                    - "0.0"
                    - -nhl
                    - "2"
                    - -sz
                    - "64"
                    - "64"
                    - -a
                    - tanh
                    - -w_i
                    - xavier
                codePath: src\train_sweep.py
                codePathLocal: src\train_sweep.py
                cpu_count: 4
                cpu_count_logical: 8
                disk:
                    /:
                        total: "510924943360"
                        used: "250523725824"
                email: ge26z812@smail.iitm.ac.in
                executable: C:\Users\HP\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe
                host: DESKTOP-TEQEIB7
                memory:
                    total: "16985714688"
                os: Windows-11-10.0.22631-SP0
                program: C:\Users\HP\Downloads\submission_structure_fixed\src\train_sweep.py
                python: CPython 3.13.12
                root: C:\Users\HP\Downloads\submission_structure_fixed
                startedAt: "2026-03-07T10:33:40.186041Z"
                writerId: hdrx3nuvs0cavaw0l16q93bs7mmvnktt
        m: []
        python_version: 3.13.12
        t:
            "1":
                - 2
                - 3
                - 5
                - 53
            "2":
                - 2
                - 3
                - 5
                - 53
            "3":
                - 2
                - 16
            "4": 3.13.12
            "5": 0.25.0
            "8":
                - 3
            "12": 0.25.0
            "13": windows-amd64
activation:
    value: tanh
batch_size:
    value: 64
dataset:
    value: mnist
epochs:
    value: 5
hidden_size:
    value:
        - 64
        - 64
learning_rate:
    value: 0.0005
loss:
    value: cross_entropy
num_layers:
    value: 2
optimizer:
    value: momentum
weight_decay:
    value: 0
weight_init:
    value: xavier
